[project]
dependencies = [
    "mkdocs>=1.6.0",
    "mkdocs-material>=9.5.0",
    "mkdocs-git-authors-plugin>=0.9.0",
    "mkdocs-git-revision-date-localized-plugin>=1.2.0",
]
name = "HFLSers"
version = "0.1.0"
description = "A site for HFLSers"
readme = "README.md"
requires-python = ">=3.13"
