[project]
site_name = "HFLSers"
site_author = "HFLSers"
site_description = "This is for HFLSers."
site_url = "https://HFLSers.github.io"

repo_url = "https://github.com/HFLSers/HFLSers.github.io"
repo_name = "HFLSers/HFLSers.github.io"
repo = "fontawesome/brands/git-alt"

copyright = "Copyright &copy; 2026 HFLSers"

# Navigation
nav = [
    { "主页" = [
        { "关于" = "index.md" },
        { "投稿指南" = "post.md" },
    ] },
    { "学术探究" = "study/index.md" },
    { "社团活动" = "club/index.md" },
    { "校园生活" = "life/index.md" },
    { "校友风采" = "alumni/index.md" },
    { "聊天" = "chat/index.md" },
]

extra_javascript = [
    "javascripts/katex.js",
    "https://unpkg.com/katex@0/dist/katex.min.js",
    "https://unpkg.com/katex@0/dist/contrib/auto-render.min.js",
    "https://cdn.jsdelivr.net/npm/svg-pan-zoom@3.5.0/dist/svg-pan-zoom.min.js",
]

extra_css = ["https://unpkg.com/katex@0/dist/katex.min.css"]

[project.theme]
# logo = "images/logo.png"
# favicon = "images/favicon.png"
features = [
    "navigation.tabs",
    "navigation.sections",
    "navigation.path",
    "navigation.footer",
    "content.code.copy",
]
custom_dir = "overrides"

[[project.theme.palette]]
media = "(prefers-color-scheme)"
toggle.icon = "lucide/monitor"
toggle.name = "Switch to light mode"
primary = "indigo"
accent = "indigo"

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"
primary = "indigo"
accent = "indigo"

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to system preference"
primary = "indigo"
accent = "indigo"

[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/HFLSers"

[project.markdown_extensions.pymdownx.snippets]

[project.markdown_extensions.abbr]
[project.markdown_extensions.admonition]
[project.markdown_extensions.attr_list]
[project.markdown_extensions.def_list]
[project.markdown_extensions.footnotes]
[project.markdown_extensions.md_in_html]
[project.markdown_extensions.toc]
permalink = true
[project.markdown_extensions.pymdownx.arithmatex]
generic = true
[project.markdown_extensions.pymdownx.betterem]
smart_enable = "all"
[project.markdown_extensions.pymdownx.caret]
[project.markdown_extensions.pymdownx.details]
[project.markdown_extensions.pymdownx.emoji]
emoji_generator = "zensical.extensions.emoji.to_svg"
emoji_index = "zensical.extensions.emoji.twemoji"
[project.markdown_extensions.pymdownx.highlight]
[project.markdown_extensions.pymdownx.inlinehilite]
[project.markdown_extensions.pymdownx.keys]
[project.markdown_extensions.pymdownx.mark]
[project.markdown_extensions.pymdownx.smartsymbols]
[project.markdown_extensions.pymdownx.superfences]
[project.markdown_extensions.pymdownx.tabbed]
alternate_style = true
[project.markdown_extensions.pymdownx.tasklist]
custom_checkbox = true
[project.markdown_extensions.pymdownx.tilde]
